# Generated by Django 4.1.2 on 2022-10-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
