# Generated by Django 4.1.2 on 2022-10-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ManyToManyField(to='post.post'),
        ),
    ]
